name: Pr

on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
          check-latest: true
      - run: yarn install
      - run: yarn lint
      - run: yarn test --coverage
      - run: yarn build
