name: Pr

on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@master
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: lint
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build
